micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix_grpc?useTimezone=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update

itau:
  url: http://localhost:9091
